import Head from "next/head";
import Navbar from "../components/Navbar"; // Adjust the path as needed
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Owambe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        {/* Wrapper for content and navbar */}
        <div className="flex flex-col flex-grow overflow-hidden">
          {/* Main content area that is scrollable */}
          <main className="flex-grow overflow-y-auto p-4 md:p-8 pb-20">
            {children}
          </main>

          {/* Fixed Navbar at the bottom */}
          <Navbar />
        </div>
      </body>
    </html>
  );
}
